<a href="https://colab.research.google.com/github/NEHA1039/DSBDL-LAB/blob/main/dsbda_assignment_6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


In [ ]:
df=pd.read_csv('/content/iris.csv')

In [ ]:
df.head(2)

,Id,SepalLength,SepalWidth,PetalLength,PetalWidth,Species
0,1,5.1,3.5,1.4,0.2,Setosa
1,2,4.9,3.0,1.4,0.2,Setosa


In [ ]:
df.tail(2)

,Id,SepalLength,SepalWidth,PetalLength,PetalWidth,Species
148,149,6.2,3.4,5.4,2.3,Virginica
149,150,5.9,3.0,5.1,1.8,Virginica


In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   Id           150 non-null    int64  
 1   SepalLength  148 non-null    float64
 2   SepalWidth   150 non-null    float64
 3   PetalLength  150 non-null    float64
 4   PetalWidth   148 non-null    float64
 5   Species      150 non-null    object 
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB


In [ ]:
df.describe()

,Id,SepalLength,SepalWidth,PetalLength,PetalWidth
count,150.000000,148.000000,150.000000,150.000000,148.000000
mean,75.500000,5.856757,3.054000,3.758667,1.197973
std,43.445368,0.825459,0.433594,1.764420,0.760278
min,1.000000,4.300000,2.000000,1.000000,0.100000
25%,38.250000,5.100000,2.800000,1.600000,0.300000
50%,75.500000,5.800000,3.000000,4.350000,1.300000
75%,112.750000,6.400000,3.300000,5.100000,1.800000
max,150.000000,7.900000,4.400000,6.900000,2.500000


In [ ]:
x=df[['SepalLength','SepalWidth','PetalLength','PetalWidth']].dropna()
y=df['Species'].loc[x.index]

In [ ]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(
    x,y,test_size=0.2,random_state=0, stratify=y
)

In [ ]:
from sklearn .preprocessing import StandardScaler
sc=StandardScaler()
xtrain=sc.fit_transform(xtrain)
xtest=sc.transform(xtest)

In [ ]:
from sklearn.naive_bayes import GaussianNB
guassian = GaussianNB()
guassian.fit(xtrain, ytrain)

GaussianNB()

In [ ]:
y_pred=guassian.predict(xtest)

In [ ]:
from sklearn.metrics import precision_score,confusion_matrix,accuracy_score,recall_score
cm= confusion_matrix(ytest, y_pred)
accuracy_val = accuracy_score(ytest,y_pred)
error_rate=1-accuracy_val
print("Accuracy:", accuracy_val)


Accuracy: 0.9666666666666667


In [ ]:
print("Precision:",precision_score(ytest,y_pred, average='weighted'))


Precision: 0.9696969696969696


In [ ]:
print("Recall:",recall_score(ytest,y_pred, average='weighted'))

Recall: 0.9666666666666667


In [ ]:
print("Error rate:",error_rate)

Error rate: 0.033333333333333326


In [ ]:
print("Confusion matrix:\n",cm)

Confusion matrix:
 [[10  0  0]
 [ 0 10  0]
 [ 0  1  9]]
